# Change variables in this file to reflect your needs, wishes, constraints
PROGRAM = veriT

# Choose internal or minisat for SAT engine
SAT_ENGINE = internal
export SAT_ENGINE

NUMBER_REPRESENTATION = NUMBER_GMP_RATIONAL_INFINITY
export NUMBER_REPRESENTATION

PROOF_PRODUCTION = NO
# PROOF_PRODUCTION = YES

# Installation directories
PREFIX      = ${HOME}
PREFIX_BIN  = ${PREFIX}/bin
DISTRIB = 1
